package com.github.librarian.model.mapper;

import com.github.librarian.model.entity.Book;
import com.github.librarian.model.entity.BookExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK
     *
     * @mbg.generated Mon May 01 16:23:46 CST 2017
     */
    long countByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK
     *
     * @mbg.generated Mon May 01 16:23:46 CST 2017
     */
    int deleteByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK
     *
     * @mbg.generated Mon May 01 16:23:46 CST 2017
     */
    int deleteByPrimaryKey(String isbn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK
     *
     * @mbg.generated Mon May 01 16:23:46 CST 2017
     */
    int insert(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK
     *
     * @mbg.generated Mon May 01 16:23:46 CST 2017
     */
    int insertSelective(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK
     *
     * @mbg.generated Mon May 01 16:23:46 CST 2017
     */
    List<Book> selectByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK
     *
     * @mbg.generated Mon May 01 16:23:46 CST 2017
     */
    Book selectByPrimaryKey(String isbn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK
     *
     * @mbg.generated Mon May 01 16:23:46 CST 2017
     */
    int updateByExampleSelective(@Param("record") Book record, @Param("example") BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK
     *
     * @mbg.generated Mon May 01 16:23:46 CST 2017
     */
    int updateByExample(@Param("record") Book record, @Param("example") BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK
     *
     * @mbg.generated Mon May 01 16:23:46 CST 2017
     */
    int updateByPrimaryKeySelective(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK
     *
     * @mbg.generated Mon May 01 16:23:46 CST 2017
     */
    int updateByPrimaryKey(Book record);
}