package com.github.librarian.model.mapper;

import com.github.librarian.model.entity.BookBorrowingRecord;
import com.github.librarian.model.entity.BookBorrowingRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookBorrowingRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK_BORROWING_RECORD
     *
     * @mbg.generated Wed Apr 26 17:43:10 CST 2017
     */
    long countByExample(BookBorrowingRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK_BORROWING_RECORD
     *
     * @mbg.generated Wed Apr 26 17:43:10 CST 2017
     */
    int deleteByExample(BookBorrowingRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK_BORROWING_RECORD
     *
     * @mbg.generated Wed Apr 26 17:43:10 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK_BORROWING_RECORD
     *
     * @mbg.generated Wed Apr 26 17:43:10 CST 2017
     */
    int insert(BookBorrowingRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK_BORROWING_RECORD
     *
     * @mbg.generated Wed Apr 26 17:43:10 CST 2017
     */
    int insertSelective(BookBorrowingRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK_BORROWING_RECORD
     *
     * @mbg.generated Wed Apr 26 17:43:10 CST 2017
     */
    List<BookBorrowingRecord> selectByExample(BookBorrowingRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK_BORROWING_RECORD
     *
     * @mbg.generated Wed Apr 26 17:43:10 CST 2017
     */
    BookBorrowingRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK_BORROWING_RECORD
     *
     * @mbg.generated Wed Apr 26 17:43:10 CST 2017
     */
    int updateByExampleSelective(@Param("record") BookBorrowingRecord record, @Param("example") BookBorrowingRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK_BORROWING_RECORD
     *
     * @mbg.generated Wed Apr 26 17:43:10 CST 2017
     */
    int updateByExample(@Param("record") BookBorrowingRecord record, @Param("example") BookBorrowingRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK_BORROWING_RECORD
     *
     * @mbg.generated Wed Apr 26 17:43:10 CST 2017
     */
    int updateByPrimaryKeySelective(BookBorrowingRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK_BORROWING_RECORD
     *
     * @mbg.generated Wed Apr 26 17:43:10 CST 2017
     */
    int updateByPrimaryKey(BookBorrowingRecord record);
}