package com.github.librarian.model.entity;

public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOOK.ISBN
     *
     * @mbg.generated Wed Apr 26 17:43:10 CST 2017
     */
    private String isbn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOOK.NAME
     *
     * @mbg.generated Wed Apr 26 17:43:10 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOOK.INTRO
     *
     * @mbg.generated Wed Apr 26 17:43:10 CST 2017
     */
    private String intro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOOK.BOOKCOUNT
     *
     * @mbg.generated Wed Apr 26 17:43:10 CST 2017
     */
    private Integer bookcount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOOK.ISBN
     *
     * @return the value of BOOK.ISBN
     *
     * @mbg.generated Wed Apr 26 17:43:10 CST 2017
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOOK.ISBN
     *
     * @param isbn the value for BOOK.ISBN
     *
     * @mbg.generated Wed Apr 26 17:43:10 CST 2017
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn == null ? null : isbn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOOK.NAME
     *
     * @return the value of BOOK.NAME
     *
     * @mbg.generated Wed Apr 26 17:43:10 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOOK.NAME
     *
     * @param name the value for BOOK.NAME
     *
     * @mbg.generated Wed Apr 26 17:43:10 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOOK.INTRO
     *
     * @return the value of BOOK.INTRO
     *
     * @mbg.generated Wed Apr 26 17:43:10 CST 2017
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOOK.INTRO
     *
     * @param intro the value for BOOK.INTRO
     *
     * @mbg.generated Wed Apr 26 17:43:10 CST 2017
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOOK.BOOKCOUNT
     *
     * @return the value of BOOK.BOOKCOUNT
     *
     * @mbg.generated Wed Apr 26 17:43:10 CST 2017
     */
    public Integer getBookcount() {
        return bookcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOOK.BOOKCOUNT
     *
     * @param bookcount the value for BOOK.BOOKCOUNT
     *
     * @mbg.generated Wed Apr 26 17:43:10 CST 2017
     */
    public void setBookcount(Integer bookcount) {
        this.bookcount = bookcount;
    }
}