package com.github.librarian.model.entity;

import com.github.librarian.model.enums.BorrowerStatus;

public class Borrower {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BORROWER.ID
     *
     * @mbg.generated Mon May 01 16:23:46 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BORROWER.NAME
     *
     * @mbg.generated Mon May 01 16:23:46 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BORROWER.EMAIL
     *
     * @mbg.generated Mon May 01 16:23:46 CST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BORROWER.PASSWORD
     *
     * @mbg.generated Mon May 01 16:23:46 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BORROWER.STATUS
     *
     * @mbg.generated Mon May 01 16:23:46 CST 2017
     */
    private BorrowerStatus status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BORROWER.ID
     *
     * @return the value of BORROWER.ID
     *
     * @mbg.generated Mon May 01 16:23:46 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BORROWER.ID
     *
     * @param id the value for BORROWER.ID
     *
     * @mbg.generated Mon May 01 16:23:46 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BORROWER.NAME
     *
     * @return the value of BORROWER.NAME
     *
     * @mbg.generated Mon May 01 16:23:46 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BORROWER.NAME
     *
     * @param name the value for BORROWER.NAME
     *
     * @mbg.generated Mon May 01 16:23:46 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BORROWER.EMAIL
     *
     * @return the value of BORROWER.EMAIL
     *
     * @mbg.generated Mon May 01 16:23:46 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BORROWER.EMAIL
     *
     * @param email the value for BORROWER.EMAIL
     *
     * @mbg.generated Mon May 01 16:23:46 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BORROWER.PASSWORD
     *
     * @return the value of BORROWER.PASSWORD
     *
     * @mbg.generated Mon May 01 16:23:46 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BORROWER.PASSWORD
     *
     * @param password the value for BORROWER.PASSWORD
     *
     * @mbg.generated Mon May 01 16:23:46 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BORROWER.STATUS
     *
     * @return the value of BORROWER.STATUS
     *
     * @mbg.generated Mon May 01 16:23:46 CST 2017
     */
    public BorrowerStatus getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BORROWER.STATUS
     *
     * @param status the value for BORROWER.STATUS
     *
     * @mbg.generated Mon May 01 16:23:46 CST 2017
     */
    public void setStatus(BorrowerStatus status) {
        this.status = status;
    }
}