INSERT INTO borrower (ID, Name, Email, Password, Status) VALUES (1,'zack','zack@lib.com','123456',1);
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (50,'zack@lib.com','123456',1,'Ainsley ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (2,'zack@lib.com','123456',1,'Alaia   ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (3,'zack@lib.com','123456',1,'Alessia ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (4,'zack@lib.com','123456',1,'Alina   ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (5,'zack@lib.com','123456',1,'Alivia  ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (6,'zack@lib.com','123456',1,'Amoret  ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (7,'zack@lib.com','123456',1,'Asha    ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (8,'zack@lib.com','123456',1,'Augusta ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (9,'zack@lib.com','123456',1,'Aveline ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (10,'zack@lib.com','123456',1,'Bea     ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (11,'zack@lib.com','123456',1,'Betty   ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (12,'zack@lib.com','123456',1,'Brooke  ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (13,'zack@lib.com','123456',1,'Bryony  ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (14,'zack@lib.com','123456',1,'Camila  ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (15,'zack@lib.com','123456',1,'Eira    ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (16,'zack@lib.com','123456',1,'Eleanora');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (17,'zack@lib.com','123456',1,'Ellen   ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (18,'zack@lib.com','123456',1,'Emerson ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (19,'zack@lib.com','123456',1,'Estelle ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (20,'zack@lib.com','123456',1,'Everly  ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (21,'zack@lib.com','123456',1,'Gaia    ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (22,'zack@lib.com','123456',1,'Indie   ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (23,'zack@lib.com','123456',1,'Ione    ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (24,'zack@lib.com','123456',1,'Isobel  ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (25,'zack@lib.com','123456',1,'Jocelyn ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (26,'zack@lib.com','123456',1,'Judith  ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (27,'zack@lib.com','123456',1,'Kaia    ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (28,'zack@lib.com','123456',1,'Kalila  ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (29,'zack@lib.com','123456',1,'Liliana ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (30,'zack@lib.com','123456',1,'Lucille ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (31,'zack@lib.com','123456',1,'Marin   ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (32,'zack@lib.com','123456',1,'Marley  ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (33,'zack@lib.com','123456',1,'Meilani ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (34,'zack@lib.com','123456',1,'Mireille');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (35,'zack@lib.com','123456',1,'Norah   ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (36,'zack@lib.com','123456',1,'Orla    ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (37,'zack@lib.com','123456',1,'Paloma  ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (38,'zack@lib.com','123456',1,'Pandora ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (39,'zack@lib.com','123456',1,'Peyton  ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (40,'zack@lib.com','123456',1,'Polly   ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (41,'zack@lib.com','123456',1,'Primrose');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (42,'zack@lib.com','123456',1,'Remi    ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (43,'zack@lib.com','123456',1,'Ruth    ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (44,'zack@lib.com','123456',1,'Sasha   ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (45,'zack@lib.com','123456',1,'Tallulah');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (46,'zack@lib.com','123456',1,'Teagan  ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (47,'zack@lib.com','123456',1,'Tove    ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (48,'zack@lib.com','123456',1,'Vanessa ');
INSERT INTO borrower (ID,  Email, Password, Status,Name) VALUES (49,'zack@lib.com','123456',1,'Veronica');
UPDATE borrower set Email = Name+'@lib.com';

