INSERT INTO borrower ( Name, Email, Password, Status) VALUES ('zack','zack@lib.com','123456',1);
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Ainsley ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Alaia   ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Alessia ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Alina   ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Alivia  ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Amoret  ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Asha    ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Augusta ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Aveline ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Bea     ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Betty   ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Brooke  ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Bryony  ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Camila  ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Eira    ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Eleanora');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Ellen   ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Emerson ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Estelle ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Everly  ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Gaia    ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Indie   ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Ione    ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Isobel  ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Jocelyn ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Judith  ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Kaia    ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Kalila  ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Liliana ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Lucille ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Marin   ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Marley  ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Meilani ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Mireille');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Norah   ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Orla    ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Paloma  ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Pandora ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Peyton  ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Polly   ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Primrose');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Remi    ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Ruth    ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Sasha   ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Tallulah');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Teagan  ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Tove    ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Vanessa ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Veronica');
UPDATE borrower set Email = Name+'@lib.com';

insert into book (ISBN,Name,Intro,BookCount) values ('9047-64-438-933-93','capabilities spaces list be always','Dynamic spaces to is painful at it to If how of or conditionally of ',32);
insert into book (ISBN,Name,Intro,BookCount) values ('3694-85-717-410-72','with concatenate SQL together understand','painful experience One SQL to painful conditionally to always SQL conditionally you or features SQL any painful comma end ',58);
insert into book (ISBN,Name,Intro,BookCount) values ('1516-13-836-183-42','its is SQL to similar','similar or the similar columns SQL end to strings capabilities One ',65);
insert into book (ISBN,Name,Intro,BookCount) values ('7679-43-751-920-76','been SQL conditionally has the','a deal of of any experience can to painful at conditionally been deal can a has experience to a end of ',24);
insert into book (ISBN,Name,Intro,BookCount) values ('4582-88-395-275-15','the at have If similar','of with sure list with SQL any been making to have not can with spaces ',23);
insert into book (ISBN,Name,Intro,BookCount) values ('9778-91-197-734-97','list is JDBC been to','SQL list similar of its comma to of painful JDBC forget capabilities of ',33);
insert into book (ISBN,Name,Intro,BookCount) values ('5715-46-689-209-50','to the MyBatis to painful','SQL SQL SQL always to you the of together can features the you ',34);
insert into book (ISBN,Name,Intro,BookCount) values ('3965-65-174-865-54','any how is at not','most strings you concatenate powerful conditionally it making downright of SQL forget concatenate of ',37);
insert into book (ISBN,Name,Intro,BookCount) values ('6604-75-727-619-23','capabilities of to you to','spaces with be SQL at to painful with understand JDBC its most If JDBC ',4);
insert into book (ISBN,Name,Intro,BookCount) values ('4011-79-918-583-41','omit or list columns a','end experience always has you painful be making list of to forget ',65);
insert into book (ISBN,Name,Intro,BookCount) values ('7456-11-383-507-98','you of deal of to','its with experience to with end it concatenate with any can conditionally capabilities powerful sure columns can the you capabilities how ',3);
insert into book (ISBN,Name,Intro,BookCount) values ('6293-52-281-984-68','always has If forget list','to omit painful to of is has is of MyBatis If SQL any the ',92);
insert into book (ISBN,Name,Intro,BookCount) values ('2797-50-728-728-82','any always be experience painful','sure One of Dynamic together of of comma or making with similar at with Dynamic with with understand columns painful a it framework spaces ',89);
insert into book (ISBN,Name,Intro,BookCount) values ('2249-46-452-722-68','list One of is SQL','the end you a you to have a always been sure with conditionally the ',65);
insert into book (ISBN,Name,Intro,BookCount) values ('8852-55-787-309-13','experience omit One capabilities of','the end conditionally how features columns JDBC or of at or how JDBC framework to concatenate downright ',76);
insert into book (ISBN,Name,Intro,BookCount) values ('2134-11-653-484-11','columns making with list of','powerful deal to it to spaces can any is of been end Dynamic a of comma painful conditionally not understand is painful of columns understand ',87);
insert into book (ISBN,Name,Intro,BookCount) values ('2297-14-957-145-53','have a SQL painful always','the SQL or painful SQL together it comma JDBC you SQL sure making with of with how at of can columns list painful been ',61);
insert into book (ISBN,Name,Intro,BookCount) values ('3800-13-824-160-91','be to any list is','columns can making a sure Dynamic the forget you experience spaces is ',78);
insert into book (ISBN,Name,Intro,BookCount) values ('4615-82-990-288-19','always SQL JDBC you of','concatenate painful to it columns be to omit strings of similar of to ',63);
insert into book (ISBN,Name,Intro,BookCount) values ('8108-86-813-705-83','columns not to list MyBatis','columns end Dynamic has of features spaces of spaces JDBC always experience end at to has been ',73);
insert into book (ISBN,Name,Intro,BookCount) values ('7952-26-576-586-89','how has its MyBatis comma','or of painful conditionally JDBC to of sure powerful been omit SQL understand deal to ',21);
insert into book (ISBN,Name,Intro,BookCount) values ('8248-32-108-565-83','Dynamic columns you always framework','at its with always most painful of spaces If of comma always you the spaces MyBatis ',72);
insert into book (ISBN,Name,Intro,BookCount) values ('3494-90-980-846-35','Dynamic not painful framework to','If deal SQL to has omit a how making downright SQL at be SQL SQL is or ',86);
insert into book (ISBN,Name,Intro,BookCount) values ('3350-77-467-763-12','together of SQL or SQL','any with of it strings making Dynamic can of with MyBatis framework painful downright ',54);
insert into book (ISBN,Name,Intro,BookCount) values ('4071-28-897-257-47','similar of Dynamic most framework','be concatenate with MyBatis deal omit any have is to at columns any to of painful ',40);
insert into book (ISBN,Name,Intro,BookCount) values ('6185-84-777-384-91','capabilities columns conditionally One features','most powerful any SQL similar of similar omit to framework conditionally list end how ',3);
insert into book (ISBN,Name,Intro,BookCount) values ('2139-40-397-450-73','a understand has how most','JDBC or its strings omit If to JDBC of comma or list most SQL One with comma end deal to columns any not ',20);
insert into book (ISBN,Name,Intro,BookCount) values ('2496-68-939-457-58','to always painful list a','JDBC omit painful of with Dynamic understand painful most always can been sure can conditionally its If has ',57);
insert into book (ISBN,Name,Intro,BookCount) values ('7266-34-170-583-77','SQL of been or be','have features or you at making concatenate strings columns been painful to a painful spaces ',65);
insert into book (ISBN,Name,Intro,BookCount) values ('8127-84-884-826-33','conditionally of any of together','JDBC powerful understand most you its framework always have painful of been One at SQL downright One SQL or ',74);
insert into book (ISBN,Name,Intro,BookCount) values ('9386-21-433-911-90','of how to been concatenate','of understand Dynamic been the or can One JDBC a any to spaces SQL SQL at or ',92);
insert into book (ISBN,Name,Intro,BookCount) values ('4473-94-526-121-28','If together have list conditionally','deal comma of or it MyBatis deal a SQL capabilities columns of to omit of painful of painful spaces to have not of ',7);
insert into book (ISBN,Name,Intro,BookCount) values ('7775-87-400-430-33','sure the capabilities always of','any framework capabilities spaces omit with features to to SQL Dynamic SQL or ',79);
insert into book (ISBN,Name,Intro,BookCount) values ('5179-61-688-702-80','at a to or any','similar to you to you framework any painful with making end downright deal the how SQL experience be making ',31);
insert into book (ISBN,Name,Intro,BookCount) values ('8517-20-656-364-53','conditionally If most how columns','list at of with end painful sure of comma the deal painful ',73);
insert into book (ISBN,Name,Intro,BookCount) values ('7349-40-437-713-47','JDBC sure or If painful','sure spaces any JDBC not most the to you SQL or a a SQL ',93);
insert into book (ISBN,Name,Intro,BookCount) values ('8267-96-838-433-42','how of downright or you','together framework features columns have capabilities of any list deal Dynamic comma sure columns most strings ',1);
insert into book (ISBN,Name,Intro,BookCount) values ('1435-33-476-736-83','list end strings comma end','has any spaces any any most the Dynamic features at or or always is downright similar to been JDBC been MyBatis omit be ',49);
insert into book (ISBN,Name,Intro,BookCount) values ('2286-16-285-997-46','deal be concatenate to to','the of If has list painful features Dynamic at it ',51);
insert into book (ISBN,Name,Intro,BookCount) values ('7712-90-176-879-89','to Dynamic is SQL framework','similar forget framework MyBatis Dynamic you JDBC or to its concatenate been of it spaces always conditionally concatenate ',89);
insert into book (ISBN,Name,Intro,BookCount) values ('2629-15-472-883-75','list list of you SQL','Dynamic you framework or Dynamic its capabilities SQL its spaces painful together a forget MyBatis has One strings One Dynamic features ',45);
insert into book (ISBN,Name,Intro,BookCount) values ('8143-65-212-944-54','One can spaces columns together','sure sure painful SQL with SQL is SQL be of to of deal capabilities sure spaces to of SQL how painful ',6);
insert into book (ISBN,Name,Intro,BookCount) values ('5300-22-378-200-15','together not deal columns at','of a of features is can forget One conditionally framework together SQL One it not you conditionally list of painful to strings a ',53);
insert into book (ISBN,Name,Intro,BookCount) values ('8842-65-315-263-45','to If deal similar to','features of you of of to is conditionally the painful at framework of Dynamic JDBC how columns omit at most ',60);
insert into book (ISBN,Name,Intro,BookCount) values ('8754-50-969-741-93','of understand the to Dynamic','understand making with of not the a making with at of deal how has is spaces features most ',95);
insert into book (ISBN,Name,Intro,BookCount) values ('3445-48-286-327-48','understand comma columns Dynamic how','of understand capabilities comma Dynamic of spaces sure is painful painful been with the conditionally have omit painful most always columns always sure with any ',45);
insert into book (ISBN,Name,Intro,BookCount) values ('4882-43-704-234-23','or Dynamic conditionally how downright','One capabilities it be of any similar how downright to end to MyBatis Dynamic to similar how of its with ',35);
insert into book (ISBN,Name,Intro,BookCount) values ('3295-45-920-498-78','of similar of be downright','painful a or its the One If to or making capabilities with features or forget to ',77);
insert into book (ISBN,Name,Intro,BookCount) values ('1366-91-869-752-80','list of has any most','similar painful a of JDBC at strings or to with to spaces a spaces of to or the of ',93);
insert into book (ISBN,Name,Intro,BookCount) values ('8439-38-282-216-85','forget capabilities framework of of','of most strings making the features One a capabilities framework strings framework how you its any is omit list painful have or ',77);

