INSERT INTO borrower ( Name, Email, Password, Status) VALUES ('zack','zack@lib.com','123456',1);
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Ainsley ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Alaia   ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Alessia ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Alina   ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Alivia  ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Amoret  ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Asha    ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Augusta ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Aveline ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Bea     ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Betty   ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Brooke  ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Bryony  ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Camila  ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Eira    ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Eleanora');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Ellen   ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Emerson ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Estelle ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Everly  ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Gaia    ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Indie   ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Ione    ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Isobel  ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Jocelyn ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Judith  ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Kaia    ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Kalila  ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Liliana ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Lucille ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Marin   ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Marley  ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Meilani ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Mireille');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Norah   ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Orla    ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Paloma  ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Pandora ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Peyton  ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Polly   ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Primrose');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Remi    ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Ruth    ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Sasha   ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Tallulah');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Teagan  ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Tove    ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Vanessa ');
INSERT INTO borrower (  Email, Password, Status,Name) VALUES ('zack@lib.com','123456',1,'Veronica');
UPDATE borrower set Email = Name+'@lib.com';

